//! Auto-generated by nether-export - DO NOT EDIT
//!
//! This module provides access to all assets defined in assets.toml.
//! Call `load()` during your game's `init()` to load all assets.

#![allow(dead_code)]

// Embedded asset data
static CUBE_MESH: &[u8] = include_bytes!("assets//cube.nczxmesh");
static CHECKERBOARD_TEX: &[u8] = include_bytes!("assets//checkerboard.nczxtex");

// FFI functions for loading assets
extern "C" {
    fn rom_mesh(data_ptr: u32, data_len: u32) -> u32;
    fn rom_texture(data_ptr: u32, data_len: u32) -> u32;
}

/// Loaded asset handles
#[derive(Debug, Clone, Copy)]
pub struct Assets {
    /// Mesh handle for 'cube'
    pub cube_mesh: u32,
    /// Texture handle for 'checkerboard'
    pub checkerboard_tex: u32,
}

/// Load all assets
///
/// Call this during your game's `init()` function.
/// Returns an `Assets` struct with handles to all loaded assets.
pub fn load() -> Assets {
    Assets {
        cube_mesh: unsafe { rom_mesh(CUBE_MESH.as_ptr() as u32, CUBE_MESH.len() as u32) },
        checkerboard_tex: unsafe { rom_texture(CHECKERBOARD_TEX.as_ptr() as u32, CHECKERBOARD_TEX.len() as u32) },
    }
}
