//! Nether Mist - Ambient IT generator
//!
//! 70 BPM, D minor/Aeolian, 12 channels
//! Features: Slow pads, drones, bells, atmospheric textures

use super::{make_instrument_continue, make_instrument_fade, make_sample};
use crate::synthesizers;
use nether_it::{ItFlags, ItNote, ItWriter};

/// Generate the Nether Mist IT file
pub fn generate_mist_it() -> (Vec<u8>, Vec<(&'static str, Vec<i16>)>) {
    let mut writer = ItWriter::new("Nether Mist");

    // Set up module parameters
    writer.set_channels(12);
    writer.set_speed(6); // Slow for ambient
    writer.set_tempo(70);
    writer.set_global_volume(128);
    writer.set_mix_volume(64);
    writer.set_flags(ItFlags::STEREO | ItFlags::INSTRUMENTS | ItFlags::LINEAR_SLIDES);

    // Generate and collect samples
    let mut samples = Vec::new();
    let sample_rate = 22050;

    // 1. Sub pad
    let sub_data = synthesizers::generate_pad_sub();
    samples.push(("pad_sub", sub_data));
    let sub_sample = make_sample("Sub Drone", sample_rate);
    writer.add_sample(sub_sample, &samples.last().unwrap().1);
    writer.add_instrument(make_instrument_fade("Sub Drone", 1, 512));

    // 2. Air pad
    let air_data = synthesizers::generate_pad_air();
    samples.push(("pad_air", air_data));
    let air_sample = make_sample("Air Pad", sample_rate);
    writer.add_sample(air_sample, &samples.last().unwrap().1);
    writer.add_instrument(make_instrument_fade("Air", 2, 512));

    // 3. Warm pad
    let warm_data = synthesizers::generate_pad_warm();
    samples.push(("pad_warm", warm_data));
    let warm_sample = make_sample("Warm Pad", sample_rate);
    writer.add_sample(warm_sample, &samples.last().unwrap().1);
    writer.add_instrument(make_instrument_fade("Warm", 3, 512));

    // 4. Cold pad
    let cold_data = synthesizers::generate_pad_cold();
    samples.push(("pad_cold", cold_data));
    let cold_sample = make_sample("Cold Pad", sample_rate);
    writer.add_sample(cold_sample, &samples.last().unwrap().1);
    writer.add_instrument(make_instrument_fade("Cold", 4, 512));

    // 5. Noise breath
    let breath_data = synthesizers::generate_noise_breath();
    samples.push(("noise_breath", breath_data));
    let breath_sample = make_sample("Breath", sample_rate);
    writer.add_sample(breath_sample, &samples.last().unwrap().1);
    writer.add_instrument(make_instrument_continue("Breath", 5));

    // 6. Glass bell
    let bell_data = synthesizers::generate_bell_glass();
    samples.push(("bell_glass", bell_data));
    let bell_sample = make_sample("Glass Bell", sample_rate);
    writer.add_sample(bell_sample, &samples.last().unwrap().1);
    writer.add_instrument(make_instrument_continue("Bell", 6));

    // 7. Sub bass
    let bass_data = synthesizers::generate_bass_sub();
    samples.push(("bass_sub", bass_data));
    let bass_sample = make_sample("Deep Bass", sample_rate);
    writer.add_sample(bass_sample, &samples.last().unwrap().1);
    writer.add_instrument(make_instrument_fade("Bass", 7, 256));

    // 8. Ghost lead
    let ghost_data = synthesizers::generate_lead_ghost();
    samples.push(("lead_ghost", ghost_data));
    let ghost_sample = make_sample("Ghost Lead", sample_rate);
    writer.add_sample(ghost_sample, &samples.last().unwrap().1);
    writer.add_instrument(make_instrument_fade("Ghost", 8, 384));

    // 9. Reverb sim
    let reverb_data = synthesizers::generate_reverb_sim();
    samples.push(("reverb_sim", reverb_data));
    let reverb_sample = make_sample("Reverb", sample_rate);
    writer.add_sample(reverb_sample, &samples.last().unwrap().1);
    writer.add_instrument(make_instrument_continue("Reverb", 9));

    // 10. Wind atmosphere
    let wind_data = synthesizers::generate_atmos_wind();
    samples.push(("atmos_wind", wind_data));
    let wind_sample = make_sample("Wind", sample_rate);
    writer.add_sample(wind_sample, &samples.last().unwrap().1);
    writer.add_instrument(make_instrument_continue("Wind", 10));

    // Create patterns (6 patterns, 64 rows each)
    // Pattern 0: Intro (emergence)
    let pat0 = writer.add_pattern(64);
    build_intro_pattern(&mut writer, pat0);

    // Pattern 1: A1 (texture)
    let pat1 = writer.add_pattern(64);
    build_texture_pattern(&mut writer, pat1);

    // Pattern 2: A2 (thickening)
    let pat2 = writer.add_pattern(64);
    build_thick_pattern(&mut writer, pat2);

    // Pattern 3: B (descent)
    let pat3 = writer.add_pattern(64);
    build_descent_pattern(&mut writer, pat3);

    // Pattern 4: A3 (resolution)
    let pat4 = writer.add_pattern(64);
    build_resolution_pattern(&mut writer, pat4);

    // Pattern 5: Outro
    let pat5 = writer.add_pattern(64);
    build_outro_pattern(&mut writer, pat5);

    // Order table with loop
    writer.set_orders(&[pat0, pat1, pat2, pat1, pat2, pat3, pat4, pat1, pat2, pat5]);

    writer.set_message("Nether Mist - Ambient @ 70 BPM\nD minor/Aeolian\nGenerated by gen-tracker-demo-it");

    (writer.write(), samples)
}

// D minor/Aeolian notes
// D2=26, E2=28, F2=29, G2=31, A2=33, Bb2=34, C3=36, D3=38
// D4=50, E4=52, F4=53, G4=55, A4=57, Bb4=58, C5=60, D5=62
const D2: u8 = 26;
const A2: u8 = 33;
const D3: u8 = 38;
const F3: u8 = 41;
const A3: u8 = 45;
const D4: u8 = 50;
const F4: u8 = 53;
const A4: u8 = 57;
const D5: u8 = 62;

fn build_intro_pattern(writer: &mut ItWriter, pat: u8) {
    // Intro: Emergence from silence
    // Wind fades in first
    writer.set_note(pat, 0, 9, ItNote::play_note(D3, 10, 15));

    // Sub drone enters slowly
    writer.set_note(pat, 16, 0, ItNote::play_note(D2, 1, 25));

    // Breath texture
    writer.set_note(pat, 32, 4, ItNote::play_note(D4, 5, 20));

    // Single bell at end
    writer.set_note(pat, 48, 5, ItNote::play_note(A4, 6, 35));
}

fn build_texture_pattern(writer: &mut ItWriter, pat: u8) {
    // A1: Basic texture established
    // Sub drone continues
    writer.set_note(pat, 0, 0, ItNote::play_note(D2, 1, 35));

    // Warm pad layer
    writer.set_note(pat, 0, 2, ItNote::play_note(D3, 3, 30));
    writer.set_note(pat, 32, 2, ItNote::play_note(A2, 3, 28));

    // Air pad (high)
    writer.set_note(pat, 8, 1, ItNote::play_note(D5, 2, 25));

    // Wind continues
    writer.set_note(pat, 0, 9, ItNote::play_note(D3, 10, 20));

    // Bell accents
    writer.set_note(pat, 16, 5, ItNote::play_note(A4, 6, 30));
    writer.set_note(pat, 48, 5, ItNote::play_note(F4, 6, 28));

    // Bass on root
    writer.set_note(pat, 0, 6, ItNote::play_note(D2, 7, 40));
}

fn build_thick_pattern(writer: &mut ItWriter, pat: u8) {
    // A2: More layers, thickening
    // All pads active
    writer.set_note(pat, 0, 0, ItNote::play_note(D2, 1, 38));
    writer.set_note(pat, 0, 1, ItNote::play_note(D5, 2, 28));
    writer.set_note(pat, 0, 2, ItNote::play_note(D3, 3, 32));
    writer.set_note(pat, 0, 3, ItNote::play_note(A3, 4, 25));

    // Chord change at bar 3
    writer.set_note(pat, 32, 2, ItNote::play_note(F3, 3, 30));
    writer.set_note(pat, 32, 3, ItNote::play_note(A3, 4, 26));

    // Ghost lead melody
    writer.set_note(pat, 16, 7, ItNote::play_note(D4, 8, 30));
    writer.set_note(pat, 40, 7, ItNote::play_note(F4, 8, 28));

    // Multiple bells
    writer.set_note(pat, 0, 5, ItNote::play_note(A4, 6, 32));
    writer.set_note(pat, 24, 5, ItNote::play_note(D5, 6, 28));
    writer.set_note(pat, 48, 5, ItNote::play_note(F4, 6, 25));

    // Breath texture
    writer.set_note(pat, 16, 4, ItNote::play_note(D4, 5, 22));
    writer.set_note(pat, 48, 4, ItNote::play_note(A3, 5, 20));

    // Bass movement
    writer.set_note(pat, 0, 6, ItNote::play_note(D2, 7, 42));
    writer.set_note(pat, 32, 6, ItNote::play_note(A2, 7, 38));
}

fn build_descent_pattern(writer: &mut ItWriter, pat: u8) {
    // B: Descent - darker, lower
    // Cold pad takes over
    writer.set_note(pat, 0, 3, ItNote::play_note(D3, 4, 35));
    writer.set_note(pat, 32, 3, ItNote::play_note(A2, 4, 38));

    // Sub stays low
    writer.set_note(pat, 0, 0, ItNote::play_note(D2, 1, 40));

    // Bass descends
    writer.set_note(pat, 0, 6, ItNote::play_note(D2, 7, 45));
    writer.set_note(pat, 32, 6, ItNote::play_note(A2 - 12, 7, 42)); // A1

    // Reverb swells
    writer.set_note(pat, 16, 8, ItNote::play_note(D4, 9, 30));
    writer.set_note(pat, 48, 8, ItNote::play_note(A3, 9, 28));

    // Sparse bell
    writer.set_note(pat, 32, 5, ItNote::play_note(D4, 6, 25));

    // Wind more prominent
    writer.set_note(pat, 0, 9, ItNote::play_note(D3, 10, 28));
}

fn build_resolution_pattern(writer: &mut ItWriter, pat: u8) {
    // A3: Resolution - return to warmth
    // Warm pad returns
    writer.set_note(pat, 0, 2, ItNote::play_note(D3, 3, 35));
    writer.set_note(pat, 32, 2, ItNote::play_note(F3, 3, 32));

    // Sub drone
    writer.set_note(pat, 0, 0, ItNote::play_note(D2, 1, 36));

    // Air pad
    writer.set_note(pat, 0, 1, ItNote::play_note(D5, 2, 26));

    // Ghost lead resolves
    writer.set_note(pat, 0, 7, ItNote::play_note(A4, 8, 30));
    writer.set_note(pat, 32, 7, ItNote::play_note(D4, 8, 32));

    // Bells in harmony
    writer.set_note(pat, 16, 5, ItNote::play_note(D5, 6, 30));
    writer.set_note(pat, 40, 5, ItNote::play_note(A4, 6, 28));

    // Bass on root
    writer.set_note(pat, 0, 6, ItNote::play_note(D2, 7, 40));
}

fn build_outro_pattern(writer: &mut ItWriter, pat: u8) {
    // Outro: Fade to silence
    // Sub drone fading
    writer.set_note(pat, 0, 0, ItNote::play_note(D2, 1, 28));

    // Warm pad fades
    writer.set_note(pat, 0, 2, ItNote::play_note(D3, 3, 22));

    // Wind continues quietly
    writer.set_note(pat, 0, 9, ItNote::play_note(D3, 10, 15));

    // Final bell
    writer.set_note(pat, 32, 5, ItNote::play_note(D5, 6, 20));

    // Reverb trail
    writer.set_note(pat, 48, 8, ItNote::play_note(D4, 9, 18));
}
