//! Mode 3 Asset Preview (PRISM SURVIVORS + LUMINA DEPTHS)
//!
//! Auto-generated by: cargo run -p gen-assets -- all
//! Uses render_mode(3) for viewing generated assets.
//!
//! Controls:
//! - L1/R1: Cycle through assets
//! - A: Toggle grid
//! - START: Reset camera and auto-rotate
//! - Left Stick: Orbit camera
//! - Right Stick Y: Zoom in/out

#![no_std]
#![no_main]

proc_gen_common::asset_viewer!(3, "Mode 3 Preview (PRISM SURVIVORS + LUMINA DEPTHS)", [
    // PRISM SURVIVORS
    ("knight", "Knight"),
    ("mage", "Mage"),
    ("ranger", "Ranger"),
    ("cleric", "Cleric"),
    ("necromancer", "Necromancer"),
    ("paladin", "Paladin"),
    ("golem", "Golem"),
    ("crawler", "Crawler"),
    ("wisp", "Wisp"),
    ("skeleton", "Skeleton"),
    ("shade", "Shade"),
    ("berserker", "Berserker"),
    ("arcane_sentinel", "Arcane Sentinel"),
    ("crystal_knight", "Crystal Knight"),
    ("void_mage", "Void Mage"),
    ("golem_titan", "Golem Titan"),
    ("specter_lord", "Specter Lord"),
    ("prism_colossus", "Prism Colossus"),
    ("void_dragon", "Void Dragon"),
    ("xp_gem", "XP Gem"),
    ("coin", "Coin"),
    ("powerup_orb", "Powerup Orb"),
    ("frost_shard", "Frost Shard"),
    ("void_orb", "Void Orb"),
    ("lightning_bolt", "Lightning Bolt"),
    ("arena_floor", "Arena Floor"),
    // LUMINA DEPTHS
    ("submersible", "Submersible"),
    ("reef_fish", "Reef Fish"),
    ("sea_turtle", "Sea Turtle"),
    ("manta_ray", "Manta Ray"),
    ("moon_jelly", "Moon Jelly"),
    ("anglerfish", "Anglerfish"),
    ("blue_whale", "Blue Whale"),
    ("coral_brain", "Brain Coral"),
    ("kelp", "Kelp"),
    ("anemone", "Anemone"),
    ("vent_chimney", "Vent Chimney"),
    ("tube_worms", "Tube Worms"),
]);
