//! Exercise the player's actual build guard without compiling the player/GPU suite.
#[path = "../../../nethercore-zx/build_support/ffi.rs"]
mod build_guard;

#[test]
fn freshness_uses_contents_instead_of_checkout_timestamps() {
    use std::fs::{self, File, FileTimes};
    use std::time::{Duration, SystemTime};

    let original = std::env::current_dir().unwrap();
    let fixture = std::env::temp_dir().join(format!(
        "nethercore-ffi-freshness-{}-{}",
        std::process::id(),
        SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    fs::create_dir(&fixture).unwrap();
    fs::create_dir_all(fixture.join("include/zx")).unwrap();
    fs::create_dir(fixture.join("nethercore-zx")).unwrap();
    fs::write(fixture.join("Cargo.toml"), "[workspace]\n").unwrap();
    let templates = fixture.join("tools/ffi-gen/templates");
    fs::create_dir_all(&templates).unwrap();
    fs::write(templates.join("c_helpers.h"), "// fixture C helper\n").unwrap();
    fs::write(templates.join("zig_helpers.zig"), "// fixture Zig helper\n").unwrap();
    let source = fixture.join("include/zx/system.rs");
    let declaration = "extern \"C\" { pub fn delta_time() -> f32; }\n";
    fs::write(&source, declaration).unwrap();
    std::env::set_current_dir(fixture.join("nethercore-zx")).unwrap();

    let result = std::panic::catch_unwind(|| {
        assert_eq!(
            ffi_gen::parser::parse_ffi_file(fixture.join("include/zx"))
                .unwrap()
                .functions
                .len(),
            1
        );
        ffi_gen::generate_for_console("zx").unwrap();
        let outputs = [fixture.join("include/zx.h"), fixture.join("include/zx.zig")];
        let original_bytes: Vec<_> = outputs.iter().map(|p| fs::read(p).unwrap()).collect();
        assert!(String::from_utf8_lossy(&original_bytes[0]).contains("// fixture C helper"));
        assert!(String::from_utf8_lossy(&original_bytes[1]).contains("// fixture Zig helper"));
        for path in &outputs {
            File::options()
                .write(true)
                .open(path)
                .unwrap()
                .set_times(FileTimes::new().set_modified(SystemTime::UNIX_EPOCH))
                .unwrap();
            assert!(
                fs::metadata(&source).unwrap().modified().unwrap()
                    > fs::metadata(path).unwrap().modified().unwrap()
            );
        }
        // Git checkout order is irrelevant when generated bytes match.
        build_guard::check_ffi_freshness();
        for (path, bytes) in outputs.iter().zip(&original_bytes) {
            assert_eq!(fs::read(path).unwrap(), *bytes, "checking must not rewrite");
            assert_eq!(
                fs::metadata(path).unwrap().modified().unwrap(),
                SystemTime::UNIX_EPOCH
            );
            fs::write(path, "stale binding\n").unwrap();
            assert!(std::panic::catch_unwind(build_guard::check_ffi_freshness).is_err());
            fs::write(path, bytes).unwrap();
        }
        fs::write(templates.join("c_helpers.h"), "// changed helper\n").unwrap();
        assert!(std::panic::catch_unwind(build_guard::check_ffi_freshness).is_err());
        fs::write(templates.join("c_helpers.h"), "// fixture C helper\n").unwrap();
        // Newer generated-file timestamps must not hide changed declarations.
        fs::write(&source, declaration.replace("delta_time", "renamed_time")).unwrap();
        for path in &outputs {
            File::options()
                .write(true)
                .open(path)
                .unwrap()
                .set_times(
                    FileTimes::new().set_modified(SystemTime::now() + Duration::from_secs(60)),
                )
                .unwrap();
        }
        assert!(std::panic::catch_unwind(build_guard::check_ffi_freshness).is_err());
        fs::write(&source, declaration).unwrap();
        build_guard::check_ffi_freshness();
        fs::remove_file(&outputs[0]).unwrap();
        assert!(std::panic::catch_unwind(build_guard::check_ffi_freshness).is_err());
    });
    std::env::set_current_dir(original).unwrap();
    fs::remove_dir_all(fixture).unwrap();
    if let Err(error) = result {
        std::panic::resume_unwind(error);
    }
}
