//! Mode 2 Asset Preview (NEON DRIFT)
//!
//! Auto-generated by: cargo run -p gen-assets -- all
//! Uses render_mode(2) for viewing generated assets.
//!
//! Controls:
//! - L1/R1: Cycle through assets
//! - A: Toggle grid
//! - START: Reset camera and auto-rotate
//! - Left Stick: Orbit camera
//! - Right Stick Y: Zoom in/out

#![no_std]
#![no_main]

proc_gen_common::asset_viewer!(2, "Mode 2 Preview (NEON DRIFT)", [
    // NEON DRIFT
    ("speedster", "Speedster"),
    ("muscle", "Muscle Car"),
    ("racer", "Racer"),
    ("drift", "Drift Car"),
    ("track_straight", "Track: Straight"),
    ("track_curve_left", "Track: Curve Left"),
    ("track_tunnel", "Track: Tunnel"),
    ("track_jump", "Track: Jump Ramp"),
    ("prop_barrier", "Prop: Barrier"),
    ("prop_boost_pad", "Prop: Boost Pad"),
    ("prop_billboard", "Prop: Billboard"),
    ("prop_building", "Prop: Building"),
]);
