// Auto-generated by build.rs - DO NOT EDIT
// This file is generated from WGSL metadata blocks
//
// To regenerate, modify the @epu_meta_begin/@epu_meta_end blocks
// in shaders/epu/bounds/*.wgsl and shaders/epu/features/*.wgsl

#![allow(dead_code)]

/// Total number of defined opcodes
pub const OPCODE_COUNT: usize = 19;

/// Highest opcode number (for array sizing)
pub const MAX_OPCODE: usize = 19;

/// Kind of EPU opcode
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum OpcodeKind {
    /// Bounds opcode (defines regions)
    Bounds = 0,
    /// Radiance opcode (additive feature layer)
    Radiance = 1,
}

/// Mapping types for field values
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum MapKind {
    /// u8 mapped to 0.0..1.0
    U8_01 = 0,
    /// u8 mapped via linear interpolation between min..max
    U8Lerp = 1,
    /// u4 (nibble) mapped to 0.0..1.0
    U4_01 = 2,
    /// 16-bit octahedral direction encoding
    Dir16Oct = 3,
}

/// Information about a single EPU opcode
#[derive(Debug, Clone, Copy)]
pub struct OpcodeInfo {
    /// Opcode number (0x00..0x1F)
    pub code: u8,
    /// Opcode name (e.g., "PLANE", "RAMP")
    pub name: &'static str,
    /// Opcode kind (bounds or radiance)
    pub kind: OpcodeKind,
}

/// Specification for a single field in an EPU opcode
#[derive(Debug, Clone, Copy)]
pub struct FieldSpec {
    /// The raw field name (e.g., "intensity", "param_a")
    pub name: &'static str,
    /// Human-readable label for the UI
    pub label: &'static str,
    /// Optional unit string (e.g., "x", "tangent")
    pub unit: Option<&'static str>,
    /// Mapping type for the field value
    pub map: MapKind,
    /// Minimum value for u8_lerp mapping (0.0 for other mappings)
    pub min: f32,
    /// Maximum value for u8_lerp mapping (1.0 for other mappings)
    pub max: f32,
}

/// Opcode info indexed by opcode number (None for undefined opcodes)
pub static OPCODES: [Option<OpcodeInfo>; 32] = [
    None,
    Some(OpcodeInfo { code: 0x01, name: "RAMP", kind: OpcodeKind::Bounds }),
    Some(OpcodeInfo { code: 0x02, name: "SECTOR", kind: OpcodeKind::Bounds }),
    Some(OpcodeInfo { code: 0x03, name: "SILHOUETTE", kind: OpcodeKind::Bounds }),
    Some(OpcodeInfo { code: 0x04, name: "SPLIT", kind: OpcodeKind::Bounds }),
    Some(OpcodeInfo { code: 0x05, name: "CELL", kind: OpcodeKind::Bounds }),
    Some(OpcodeInfo { code: 0x06, name: "PATCHES", kind: OpcodeKind::Bounds }),
    Some(OpcodeInfo { code: 0x07, name: "APERTURE", kind: OpcodeKind::Bounds }),
    Some(OpcodeInfo { code: 0x08, name: "DECAL", kind: OpcodeKind::Radiance }),
    Some(OpcodeInfo { code: 0x09, name: "GRID", kind: OpcodeKind::Radiance }),
    Some(OpcodeInfo { code: 0x0A, name: "SCATTER", kind: OpcodeKind::Radiance }),
    Some(OpcodeInfo { code: 0x0B, name: "FLOW", kind: OpcodeKind::Radiance }),
    Some(OpcodeInfo { code: 0x0C, name: "TRACE", kind: OpcodeKind::Radiance }),
    Some(OpcodeInfo { code: 0x0D, name: "VEIL", kind: OpcodeKind::Radiance }),
    Some(OpcodeInfo { code: 0x0E, name: "ATMOSPHERE", kind: OpcodeKind::Radiance }),
    Some(OpcodeInfo { code: 0x0F, name: "PLANE", kind: OpcodeKind::Radiance }),
    Some(OpcodeInfo { code: 0x10, name: "CELESTIAL", kind: OpcodeKind::Radiance }),
    Some(OpcodeInfo { code: 0x11, name: "PORTAL", kind: OpcodeKind::Radiance }),
    Some(OpcodeInfo { code: 0x12, name: "LOBE", kind: OpcodeKind::Radiance }),
    Some(OpcodeInfo { code: 0x13, name: "BAND", kind: OpcodeKind::Radiance }),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
];

/// Variant names per opcode (up to 8)
pub static VARIANTS: [&[&str]; 32] = [
    &[],
    &[],
    &["BOX", "TUNNEL", "CAVE"],
    &["MOUNTAINS", "CITY", "FOREST", "DUNES", "WAVES", "RUINS", "INDUSTRIAL", "SPIRES"],
    &["HALF", "WEDGE", "CORNER", "BANDS", "CROSS", "PRISM"],
    &["GRID", "HEX", "VORONOI", "RADIAL", "SHATTER", "BRICK"],
    &["BLOBS", "ISLANDS", "DEBRIS", "MEMBRANE", "STATIC", "STREAKS"],
    &["CIRCLE", "RECT", "ROUNDED_RECT", "ARCH", "BARS", "MULTI", "IRREGULAR"],
    &[],
    &[],
    &["STARS", "DUST", "WINDOWS", "BUBBLES", "EMBERS", "RAIN", "SNOW"],
    &[],
    &["LIGHTNING", "CRACKS", "LEAD_LINES", "FILAMENTS"],
    &["CURTAINS", "PILLARS", "LASER_BARS", "RAIN_WALL", "SHARDS"],
    &["ABSORPTION", "RAYLEIGH", "MIE", "FULL", "ALIEN"],
    &["TILES", "HEX", "STONE", "SAND", "WATER", "GRATING", "GRASS", "PAVEMENT"],
    &["MOON", "SUN", "PLANET", "GAS_GIANT", "RINGED", "BINARY", "ECLIPSE"],
    &["CIRCLE", "RECT", "TEAR", "VORTEX", "CRACK", "RIFT"],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
];

/// Domain names per opcode (up to 4)
pub static DOMAINS: [&[&str]; 32] = [
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &["DIRECT3D", "AXIS_CYL", "AXIS_POLAR"],
    &[],
    &[],
    &[],
    &["DIRECT3D", "AXIS_CYL", "AXIS_POLAR", "TANGENT_LOCAL"],
    &[],
    &["DIRECT3D", "AXIS_CYL", "AXIS_POLAR", "TANGENT_LOCAL"],
    &["DIRECT3D", "AXIS_CYL", "AXIS_POLAR", "TANGENT_LOCAL"],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
];

static FIELDS_01: [FieldSpec; 5] = [
    FieldSpec { name: "intensity", label: "softness", unit: None, map: MapKind::U8Lerp, min: 0.010000, max: 0.500000 },
    FieldSpec { name: "param_a", label: "wall_r", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_b", label: "wall_g", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_c", label: "wall_b", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_d", label: "thresholds", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
];
static FIELDS_02: [FieldSpec; 5] = [
    FieldSpec { name: "intensity", label: "opening", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_a", label: "azimuth", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_b", label: "width", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_c", label: "-", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_d", label: "-", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
];
static FIELDS_03: [FieldSpec; 5] = [
    FieldSpec { name: "intensity", label: "edge_soft", unit: None, map: MapKind::U8Lerp, min: 0.005000, max: 0.100000 },
    FieldSpec { name: "param_a", label: "height", unit: None, map: MapKind::U8Lerp, min: -0.300000, max: 0.500000 },
    FieldSpec { name: "param_b", label: "roughness", unit: None, map: MapKind::U8Lerp, min: 0.100000, max: 1.000000 },
    FieldSpec { name: "param_c", label: "octaves", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_d", label: "-", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
];
static FIELDS_04: [FieldSpec; 5] = [
    FieldSpec { name: "intensity", label: "-", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_a", label: "blend_width", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_b", label: "angle", unit: Some("deg"), map: MapKind::U8Lerp, min: 0.000000, max: 180.000000 },
    FieldSpec { name: "param_c", label: "sides", unit: None, map: MapKind::U8Lerp, min: 2.000000, max: 16.000000 },
    FieldSpec { name: "param_d", label: "offset", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
];
static FIELDS_05: [FieldSpec; 5] = [
    FieldSpec { name: "intensity", label: "outline", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_a", label: "density", unit: None, map: MapKind::U8Lerp, min: 4.000000, max: 64.000000 },
    FieldSpec { name: "param_b", label: "fill", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_c", label: "gap_width", unit: None, map: MapKind::U8Lerp, min: 0.000000, max: 0.200000 },
    FieldSpec { name: "param_d", label: "seed", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
];
static FIELDS_06: [FieldSpec; 5] = [
    FieldSpec { name: "intensity", label: "-", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_a", label: "scale", unit: None, map: MapKind::U8Lerp, min: 1.000000, max: 16.000000 },
    FieldSpec { name: "param_b", label: "coverage", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_c", label: "sharpness", unit: None, map: MapKind::U8Lerp, min: 0.000000, max: 0.500000 },
    FieldSpec { name: "param_d", label: "seed", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
];
static FIELDS_07: [FieldSpec; 5] = [
    FieldSpec { name: "intensity", label: "edge_soft", unit: None, map: MapKind::U8Lerp, min: 0.005000, max: 0.100000 },
    FieldSpec { name: "param_a", label: "half_width", unit: None, map: MapKind::U8Lerp, min: 0.100000, max: 1.500000 },
    FieldSpec { name: "param_b", label: "half_height", unit: None, map: MapKind::U8Lerp, min: 0.100000, max: 1.500000 },
    FieldSpec { name: "param_c", label: "frame", unit: None, map: MapKind::U8Lerp, min: 0.020000, max: 0.500000 },
    FieldSpec { name: "param_d", label: "(varies)", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
];
static FIELDS_08: [FieldSpec; 5] = [
    FieldSpec { name: "intensity", label: "brightness", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_a", label: "shape+soft", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_b", label: "size", unit: Some("rad"), map: MapKind::U8Lerp, min: 0.000000, max: 0.500000 },
    FieldSpec { name: "param_c", label: "glow_soft", unit: None, map: MapKind::U8Lerp, min: 0.000000, max: 0.200000 },
    FieldSpec { name: "param_d", label: "phase", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
];
static FIELDS_09: [FieldSpec; 5] = [
    FieldSpec { name: "intensity", label: "brightness", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_a", label: "scale", unit: None, map: MapKind::U8Lerp, min: 1.000000, max: 64.000000 },
    FieldSpec { name: "param_b", label: "thickness", unit: None, map: MapKind::U8Lerp, min: 0.001000, max: 0.100000 },
    FieldSpec { name: "param_c", label: "pat+scroll", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_d", label: "phase", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
];
static FIELDS_0A: [FieldSpec; 5] = [
    FieldSpec { name: "intensity", label: "brightness", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_a", label: "density", unit: None, map: MapKind::U8Lerp, min: 1.000000, max: 256.000000 },
    FieldSpec { name: "param_b", label: "size", unit: Some("rad"), map: MapKind::U8Lerp, min: 0.001000, max: 0.050000 },
    FieldSpec { name: "param_c", label: "twinkle", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_d", label: "seed", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
];
static FIELDS_0B: [FieldSpec; 5] = [
    FieldSpec { name: "intensity", label: "brightness", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_a", label: "scale", unit: None, map: MapKind::U8Lerp, min: 1.000000, max: 16.000000 },
    FieldSpec { name: "param_b", label: "turbulence", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_c", label: "oct+pat", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_d", label: "phase", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
];
static FIELDS_0C: [FieldSpec; 5] = [
    FieldSpec { name: "intensity", label: "brightness", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_a", label: "count", unit: None, map: MapKind::U8Lerp, min: 1.000000, max: 16.000000 },
    FieldSpec { name: "param_b", label: "thickness", unit: None, map: MapKind::U8Lerp, min: 0.005000, max: 0.100000 },
    FieldSpec { name: "param_c", label: "jitter", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_d", label: "seed+shape", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
];
static FIELDS_0D: [FieldSpec; 5] = [
    FieldSpec { name: "intensity", label: "brightness", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_a", label: "count", unit: None, map: MapKind::U8Lerp, min: 2.000000, max: 32.000000 },
    FieldSpec { name: "param_b", label: "thickness", unit: None, map: MapKind::U8Lerp, min: 0.002000, max: 0.500000 },
    FieldSpec { name: "param_c", label: "sway", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_d", label: "phase", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
];
static FIELDS_0E: [FieldSpec; 5] = [
    FieldSpec { name: "intensity", label: "strength", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_a", label: "falloff", unit: None, map: MapKind::U8Lerp, min: 0.500000, max: 8.000000 },
    FieldSpec { name: "param_b", label: "horizon_y", unit: None, map: MapKind::U8Lerp, min: -1.000000, max: 1.000000 },
    FieldSpec { name: "param_c", label: "mie_conc", unit: None, map: MapKind::U8Lerp, min: 0.000000, max: 2.000000 },
    FieldSpec { name: "param_d", label: "mie_exp", unit: None, map: MapKind::U8Lerp, min: 4.000000, max: 128.000000 },
];
static FIELDS_0F: [FieldSpec; 5] = [
    FieldSpec { name: "intensity", label: "contrast", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_a", label: "scale", unit: Some("x"), map: MapKind::U8Lerp, min: 0.500000, max: 16.000000 },
    FieldSpec { name: "param_b", label: "gap_width", unit: None, map: MapKind::U8Lerp, min: 0.000000, max: 0.200000 },
    FieldSpec { name: "param_c", label: "roughness", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_d", label: "phase", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
];
static FIELDS_10: [FieldSpec; 5] = [
    FieldSpec { name: "intensity", label: "brightness", unit: None, map: MapKind::U8Lerp, min: 0.000000, max: 2.000000 },
    FieldSpec { name: "param_a", label: "ang_size", unit: Some("deg"), map: MapKind::U8Lerp, min: 0.500000, max: 45.000000 },
    FieldSpec { name: "param_b", label: "limb_dark", unit: None, map: MapKind::U8Lerp, min: 0.500000, max: 4.000000 },
    FieldSpec { name: "param_c", label: "phase_ang", unit: Some("deg"), map: MapKind::U8Lerp, min: 0.000000, max: 360.000000 },
    FieldSpec { name: "param_d", label: "(varies)", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
];
static FIELDS_11: [FieldSpec; 5] = [
    FieldSpec { name: "intensity", label: "glow", unit: None, map: MapKind::U8Lerp, min: 0.000000, max: 2.000000 },
    FieldSpec { name: "param_a", label: "size", unit: None, map: MapKind::U8Lerp, min: 0.050000, max: 0.800000 },
    FieldSpec { name: "param_b", label: "glow_width", unit: None, map: MapKind::U8Lerp, min: 0.010000, max: 0.300000 },
    FieldSpec { name: "param_c", label: "roughness", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_d", label: "phase", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
];
static FIELDS_12: [FieldSpec; 5] = [
    FieldSpec { name: "intensity", label: "brightness", unit: None, map: MapKind::U8Lerp, min: 0.000000, max: 2.000000 },
    FieldSpec { name: "param_a", label: "exponent", unit: None, map: MapKind::U8Lerp, min: 1.000000, max: 64.000000 },
    FieldSpec { name: "param_b", label: "falloff", unit: None, map: MapKind::U8Lerp, min: 0.500000, max: 4.000000 },
    FieldSpec { name: "param_c", label: "waveform", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_d", label: "phase", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
];
static FIELDS_13: [FieldSpec; 5] = [
    FieldSpec { name: "intensity", label: "brightness", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_a", label: "width", unit: None, map: MapKind::U8Lerp, min: 0.005000, max: 0.500000 },
    FieldSpec { name: "param_b", label: "y_offset", unit: None, map: MapKind::U8Lerp, min: -0.500000, max: 0.500000 },
    FieldSpec { name: "param_c", label: "softness", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
    FieldSpec { name: "param_d", label: "phase", unit: None, map: MapKind::U8_01, min: 0.000000, max: 1.000000 },
];

/// Field specifications per opcode
pub static FIELD_SPECS: [&[FieldSpec]; 32] = [
    &[],
    &FIELDS_01,
    &FIELDS_02,
    &FIELDS_03,
    &FIELDS_04,
    &FIELDS_05,
    &FIELDS_06,
    &FIELDS_07,
    &FIELDS_08,
    &FIELDS_09,
    &FIELDS_0A,
    &FIELDS_0B,
    &FIELDS_0C,
    &FIELDS_0D,
    &FIELDS_0E,
    &FIELDS_0F,
    &FIELDS_10,
    &FIELDS_11,
    &FIELDS_12,
    &FIELDS_13,
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
];

// ============================================================================
// Helper Functions
// ============================================================================

/// Get the name of an opcode, or "UNKNOWN" if undefined
#[inline]
pub const fn opcode_name(code: u8) -> &'static str {
    if code as usize >= OPCODES.len() {
        return "UNKNOWN";
    }
    match &OPCODES[code as usize] {
        Some(info) => info.name,
        None => "UNKNOWN",
    }
}

/// Get the kind of an opcode, or None if undefined
#[inline]
pub const fn opcode_kind(code: u8) -> Option<OpcodeKind> {
    if code as usize >= OPCODES.len() {
        return None;
    }
    match &OPCODES[code as usize] {
        Some(info) => Some(info.kind),
        None => None,
    }
}

/// Get the name of a variant for an opcode, or "" if invalid
#[inline]
pub fn variant_name(opcode: u8, variant_id: u8) -> &'static str {
    if opcode as usize >= VARIANTS.len() {
        return "";
    }
    let variants = VARIANTS[opcode as usize];
    if (variant_id as usize) < variants.len() {
        variants[variant_id as usize]
    } else {
        ""
    }
}

/// Get the name of a domain for an opcode, or "" if invalid
#[inline]
pub fn domain_name(opcode: u8, domain_id: u8) -> &'static str {
    if opcode as usize >= DOMAINS.len() {
        return "";
    }
    let domains = DOMAINS[opcode as usize];
    if (domain_id as usize) < domains.len() {
        domains[domain_id as usize]
    } else {
        ""
    }
}

/// Get the number of variants for an opcode
#[inline]
pub fn variant_count(opcode: u8) -> usize {
    if opcode as usize >= VARIANTS.len() {
        return 0;
    }
    VARIANTS[opcode as usize].len()
}

/// Get the number of domains for an opcode
#[inline]
pub fn domain_count(opcode: u8) -> usize {
    if opcode as usize >= DOMAINS.len() {
        return 0;
    }
    DOMAINS[opcode as usize].len()
}

/// Get the field specifications for an opcode
#[inline]
pub fn field_specs(opcode: u8) -> &'static [FieldSpec] {
    if opcode as usize >= FIELD_SPECS.len() {
        return &[];
    }
    FIELD_SPECS[opcode as usize]
}

/// Check if an opcode is defined
#[inline]
pub const fn is_defined(code: u8) -> bool {
    if code as usize >= OPCODES.len() {
        return false;
    }
    OPCODES[code as usize].is_some()
}
