//! Mode 3 Asset Preview (PRISM SURVIVORS + LUMINA DEPTHS)
//!
//! Auto-generated by: cargo run -p gen-assets -- all
//! Uses render_mode(3) for viewing generated assets.

#![no_std]
#![no_main]

proc_gen_common::asset_viewer!(3, "Mode 3 Preview (PRISM SURVIVORS + LUMINA DEPTHS)", [
    // PRISM SURVIVORS
    ("knight", "Knight"),
    ("mage", "Mage"),
    ("ranger", "Ranger"),
    ("cleric", "Cleric"),
    ("golem", "Golem"),
    ("crawler", "Crawler"),
    ("wisp", "Wisp"),
    ("skeleton", "Skeleton"),
    // LUMINA DEPTHS
    ("submersible", "Submersible"),
    ("reef_fish", "Reef Fish"),
    ("sea_turtle", "Sea Turtle"),
    ("manta_ray", "Manta Ray"),
    ("moon_jelly", "Moon Jelly"),
    ("anglerfish", "Anglerfish"),
    ("blue_whale", "Blue Whale"),
    ("coral_brain", "Brain Coral"),
    ("kelp", "Kelp"),
    ("anemone", "Anemone"),
    ("vent_chimney", "Vent Chimney"),
    ("tube_worms", "Tube Worms"),
]);
